services:
  api:
    container_name: mini_instagram_api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${API_PORT}:${API_PORT}"
    env_file:
      - .env
    depends_on:
      - postgres_db_container
    command: npm run start:dev

  postgres_db_container:
    container_name: mini_instagram_db
    image: postgres:14
    ports:
      - "${POSTGRES_EXPOSE_PORT}:${POSTGRES_PORT}"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - mini_instagram_data:/var/lib/postgresql/data

volumes:
  mini_instagram_data: